name: customer_beta
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  progress_dialog: ^1.2.0
  google_maps_flutter: ^0.5.22+2
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.4.1
  flutter_calendar_carousel: ^1.4.10
  grouped_buttons: ^1.0.4
  image_picker: ^0.6.3+1
  image_cropper: ^1.0.4
  webview_flutter: ^0.3.19+7
  #  emoji_picker: ^0.1.0
  file_picker: ^1.4.3+2
  qrscan: ^0.2.17
  flutter_rating_bar: ^3.0.1+1


  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git




dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo1.png
    - assets/images/login1.png
    - assets/images/back.png
    - assets/images/banner.png
    - assets/images/banner_3.png
    - assets/images/logo_text.png
    - assets/images/next.png
    - assets/images/logo_icon.png
    - assets/images/banner_2.png
    - assets/images/helpchat.png
    - assets/images/latest_news.png
    - assets/images/link_to_website.png
    - assets/images/location_coverage.png
    - assets/images/notification.png
    - assets/images/set_schedule.png
    - assets/images/tutorial.png
    - assets/images/avatar3.png
    - assets/images/avatar1.png
    - assets/images/avatar2.png
    - assets/images/avatar5.png
    - assets/images/avatar4.png
    - assets/images/qrscan.png
    - assets/images/scan_QR.png
    - assets/images/chat.png
    - assets/images/chat_active.png
    - assets/images/notification_bottom.png
    - assets/images/notification_active.png
    - assets/images/jobs.png
    - assets/images/filter_jobs.png
    - assets/images/jobs_active.png
    - assets/images/home.png
    - assets/images/home_active.png
    - assets/images/filter.png
    - assets/images/back_app_bar.png
    - assets/images/account.png
    - assets/images/account_active.png
    - assets/images/group_403.png
    - assets/images/message.png
    - assets/images/progress_report.png
    - assets/images/time_in_option1.png
    - assets/images/time_in_option2.png
    - assets/images/time_out_option2.png
    - assets/images/time_out_option1.png
    - assets/images/1_edit_profile.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/bank_account.png
    - assets/images/help.png
    - assets/images/learn_more.png
    - assets/images/location_coverage.png
    - assets/images/location_coverage_p.png
    - assets/images/logout.png
    - assets/images/my_schedule.png
    - assets/images/policy.png
    - assets/images/edit.png
    - assets/images/delete.png
    - assets/images/image20.png
    - assets/images/image21.png
    - assets/images/image22.png
    - assets/images/cert1.png
    - assets/images/cert2.png
    - assets/images/ic.png
    - assets/images/img-upload.png
    - assets/images/passport.png
    - assets/images/visa.png
    - assets/images/emoticons.png
    - assets/images/file_upload.png
    - assets/images/image_upload.png
    - assets/images/affinbank 1.png
    - assets/images/ambank 1.png
    - assets/images/bankislam 1.png
    - assets/images/bankrakyat 1.png
    - assets/images/bsn 1.png
    - assets/images/cimb 1.png
    - assets/images/Group 533.png
    - assets/images/hong leong connect 1.png
    - assets/images/hsbc 1.png
    - assets/images/maybank 1.png
    - assets/images/public bank 1.png
    - assets/images/rhb now 1.png
    - assets/images/standardchartered 1.png
    - assets/images/myself.png
    - assets/images/loved_one.png
    - assets/images/1-my_order.png
    - assets/images/2-latest_news.png
    - assets/images/3-booking_requests.png
    - assets/images/4-promotion.png
    - assets/images/5-notification_of_appointment.png
    - assets/images/6-tutorial.png
    - assets/images/7-add_person_to_care.png
    - assets/images/8-book_now.png
    - assets/images/promotion1.png
    - assets/images/promotion2.png
    - assets/images/booking.png
    - assets/images/booking_active.png
    - assets/images/summaries.png
    - assets/images/summaries_active.png
    - assets/images/booking_requests.png
    - assets/images/person_to_care.png
    - assets/images/redeem_code.png
    - assets/images/top_up.png
    - assets/images/help_account.png
    - assets/images/download_report.png
    - assets/images/time_in.png
    - assets/images/time_in2.png
    - assets/images/time_out.png
    - assets/images/time_out2.png





  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/regular.otf
        - asset: assets/fonts/bold.otf
        - asset: assets/fonts/light.otf
        - asset: assets/fonts/italic.otf
          style: italic
  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
